// <auto-generated />
using System;
using AnalyticsServer.MessagesDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticsServer.Migrations
{
    [DbContext(typeof(MessagesDb))]
    [Migration("20220131135000_Stats")]
    partial class Stats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnalyticsServer.MessagesDatabase.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CpuGnice")
                        .HasColumnType("float");

                    b.Property<double>("CpuGuest")
                        .HasColumnType("float");

                    b.Property<double>("CpuIRQ")
                        .HasColumnType("float");

                    b.Property<double>("CpuIdle")
                        .HasColumnType("float");

                    b.Property<double>("CpuIoWait")
                        .HasColumnType("float");

                    b.Property<double>("CpuNice")
                        .HasColumnType("float");

                    b.Property<double>("CpuSoft")
                        .HasColumnType("float");

                    b.Property<double>("CpuSteal")
                        .HasColumnType("float");

                    b.Property<double>("CpuSys")
                        .HasColumnType("float");

                    b.Property<double>("CpuUser")
                        .HasColumnType("float");

                    b.Property<int>("IODiskRead")
                        .HasColumnType("int");

                    b.Property<int>("IODiskWrite")
                        .HasColumnType("int");

                    b.Property<int>("IONetIn")
                        .HasColumnType("int");

                    b.Property<int>("IONetOut")
                        .HasColumnType("int");

                    b.Property<string>("IOTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamBoot")
                        .HasColumnType("int");

                    b.Property<int>("RamCache")
                        .HasColumnType("int");

                    b.Property<int>("RamSwap")
                        .HasColumnType("int");

                    b.Property<int>("RamTotal")
                        .HasColumnType("int");

                    b.Property<int>("RamUsed")
                        .HasColumnType("int");

                    b.Property<string>("SlaveId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hardware");
                });

            modelBuilder.Entity("AnalyticsServer.MessagesDatabase.HardwareDisks", b =>
                {
                    b.Property<Guid>("DiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Available")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MontedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlaveId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Use")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Used")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiskId");

                    b.ToTable("HardwareDisks");
                });
#pragma warning restore 612, 618
        }
    }
}
