// <auto-generated />
using AnalyticsServer.MessagesDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticsServer.Migrations
{
    [DbContext(typeof(MessagesDb))]
    partial class MessagesDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnalyticsServer.MessagesDatabase.Hardware", b =>
                {
                    b.Property<string>("SlaveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CpuGnice")
                        .HasColumnType("float");

                    b.Property<double>("CpuGuest")
                        .HasColumnType("float");

                    b.Property<double>("CpuIRQ")
                        .HasColumnType("float");

                    b.Property<double>("CpuIdle")
                        .HasColumnType("float");

                    b.Property<double>("CpuIoWait")
                        .HasColumnType("float");

                    b.Property<double>("CpuNice")
                        .HasColumnType("float");

                    b.Property<double>("CpuSoft")
                        .HasColumnType("float");

                    b.Property<double>("CpuSteal")
                        .HasColumnType("float");

                    b.Property<double>("CpuSys")
                        .HasColumnType("float");

                    b.Property<double>("CpuUser")
                        .HasColumnType("float");

                    b.Property<int>("IODiskRead")
                        .HasColumnType("int");

                    b.Property<int>("IODiskWrite")
                        .HasColumnType("int");

                    b.Property<int>("IONetIn")
                        .HasColumnType("int");

                    b.Property<int>("IONetOut")
                        .HasColumnType("int");

                    b.Property<string>("IOTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamBoot")
                        .HasColumnType("int");

                    b.Property<int>("RamCache")
                        .HasColumnType("int");

                    b.Property<int>("RamSwap")
                        .HasColumnType("int");

                    b.Property<int>("RamTotal")
                        .HasColumnType("int");

                    b.Property<int>("RamUsed")
                        .HasColumnType("int");

                    b.HasKey("SlaveId");

                    b.ToTable("Hardware");
                });
#pragma warning restore 612, 618
        }
    }
}
