pipeline {
 agent any
stages {
 stage('Pull') {
     steps {
      sshagent(credentials : ['6e0e3d94-0c97-447d-8e2a-d0e2857105c0']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "cd /home/AnalyticsServer/AnalyticsServer && git pull" '
               }
            }
                   }
  
   stage('Build') {
     steps {
      sshagent(credentials : ['6e0e3d94-0c97-447d-8e2a-d0e2857105c0']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "cd /home/AnalyticsServer/AnalyticsServer && dotnet publish -c Release --output /var/www/analytics" '
               }
            }
                   }

 stage ('Run') {
    steps{
        sshagent(credentials : ['6e0e3d94-0c97-447d-8e2a-d0e2857105c0']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "systemctl restart analytics.service" '
               }
         }
                 }
       }
}
