pipeline {
 agent any
stages {
 stage('Pull') {
     steps {
      sshagent(credentials : ['']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "cd /home/AnalyticsServer/AnalyticsServer && git pull" '
               }
            }
                   }
 
  stage ('Stop') {
    steps{
        sshagent(credentials : ['']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "systemctl stop analytics.service" '
               }
         }
                 }
  
   stage('Build') {
     steps {
      sshagent(credentials : ['']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "cd /home/AnalyticsServer/AnalyticsServer && dotnet publish -c Release --output /var/www/analytics" '
               }
            }
                   }

 stage ('Run') {
    steps{
        sshagent(credentials : ['']) {
            sh 'ssh -o StrictHostKeyChecking=no root@147.182.240.158 uptime'
            sh 'ssh -v root@147.182.240.158 "systemctl restart analytics.service" '
               }
         }
                 }
       }
}
